import {ChatCardProps} from '../../components/ChatCard/ChatCard';

export const chatListingMockData: ChatCardProps[] = [
  {
    name: 'Alice Johnson',
    message: 'Hey, how are you?',
    image: 'https://randomuser.me/api/portraits/women/1.jpg',
    time: '10:45 AM',
    unread: true,
    isOnline: true,
  },
  {
    name: 'Bob Smith',
    message: 'Got the files. Thanks!',
    image: 'https://randomuser.me/api/portraits/men/1.jpg',
    time: '9:15 AM',
    unread: false,
    isOnline: false,
  },
  {
    name: 'Carla Gomez',
    message: "Let's meet at 3 PM.",
    image: 'https://randomuser.me/api/portraits/women/2.jpg',
    time: '8:30 AM',
    unread: true,
    isOnline: true,
  },
  {
    name: 'Daniel Brown',
    message: "Call me when you're free.",
    image: 'https://randomuser.me/api/portraits/men/2.jpg',
    time: '7:20 AM',
    unread: false,
    isOnline: true,
  },
  {
    name: 'Emily Davis',
    message: 'Good morning! 😊',
    image: 'https://randomuser.me/api/portraits/women/3.jpg',
    time: '6:45 AM',
    unread: true,
    isOnline: false,
  },
  {
    name: 'Franklin Hall',
    message: 'See you soon.',
    image: 'https://randomuser.me/api/portraits/men/3.jpg',
    time: 'Yesterday',
    unread: false,
    isOnline: false,
  },
  {
    name: 'Grace Kelly',
    message: 'Thanks for the update.',
    image: 'https://randomuser.me/api/portraits/women/4.jpg',
    time: 'Yesterday',
    unread: true,
    isOnline: true,
  },
  {
    name: 'Hank Turner',
    message: 'Check your email.',
    image: 'https://randomuser.me/api/portraits/men/4.jpg',
    time: '2 days ago',
    unread: false,
    isOnline: true,
  },
  {
    name: 'Ivy Nguyen',
    message: 'Happy Birthday! 🎉',
    image: 'https://randomuser.me/api/portraits/women/5.jpg',
    time: '3 days ago',
    unread: true,
    isOnline: false,
  },
  {
    name: 'Jake Williams',
    message: 'Can you review the document?',
    image: 'https://randomuser.me/api/portraits/men/5.jpg',
    time: 'Last week',
    unread: false,
    isOnline: false,
  },
];
